# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/caohuiyang/Work/bbp_vcu128/xdma_bpu_ex/imports/xilinx_pcie_xdma_ref_board.xdc

# IP: ip/mult_gen_ddc/mult_gen_ddc.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_gen_ddc || ORIG_REF_NAME==mult_gen_ddc} -quiet] -quiet

# IP: ip/mult_gen_duc/mult_gen_duc.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_gen_duc || ORIG_REF_NAME==mult_gen_duc} -quiet] -quiet
