set_property SRC_FILE_INFO {cfile:/home/caohuiyang/Work/bbp_vcu128/xdma_bpu_ex/imports/xilinx_pcie_xdma_ref_board.xdc rfile:../../../imports/xilinx_pcie_xdma_ref_board.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC [get_package_pins -filter {PIN_FUNC =~ *_PERSTN0_65}] [get_ports sys_rst_n]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC [get_package_pins -of_objects [get_bels [get_sites -filter {NAME =~ *COMMON*} -of_objects [get_iobanks -of_objects [get_sites GTYE4_CHANNEL_X1Y31]]]/REFCLK0P]] [get_ports sys_clk_p]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC [get_package_pins -of_objects [get_bels [get_sites -filter {NAME =~ *COMMON*} -of_objects [get_iobanks -of_objects [get_sites GTYE4_CHANNEL_X1Y31]]]/REFCLK0N]] [get_ports sys_clk_n]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_pins -hier *sync_reg[0]/D]
