-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity apskdemod_atan2_cordic_float_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    y_in : IN STD_LOGIC_VECTOR (31 downto 0);
    x_in : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of apskdemod_atan2_cordic_float_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_3F490FDB : STD_LOGIC_VECTOR (31 downto 0) := "00111111010010010000111111011011";
    constant ap_const_lv32_C016CBE4 : STD_LOGIC_VECTOR (31 downto 0) := "11000000000101101100101111100100";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv32_4016CBE4 : STD_LOGIC_VECTOR (31 downto 0) := "01000000000101101100101111100100";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_BF490FDB : STD_LOGIC_VECTOR (31 downto 0) := "10111111010010010000111111011011";
    constant ap_const_lv32_C0490FDB : STD_LOGIC_VECTOR (31 downto 0) := "11000000010010010000111111011011";
    constant ap_const_lv32_40490FDB : STD_LOGIC_VECTOR (31 downto 0) := "01000000010010010000111111011011";
    constant ap_const_lv32_80000000 : STD_LOGIC_VECTOR (31 downto 0) := "10000000000000000000000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_7FFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "01111111111111111111111111111111";
    constant ap_const_lv32_3FC90FDB : STD_LOGIC_VECTOR (31 downto 0) := "00111111110010010000111111011011";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_BFC90FDB : STD_LOGIC_VECTOR (31 downto 0) := "10111111110010010000111111011011";
    constant ap_const_lv31_3FC90FDB : STD_LOGIC_VECTOR (30 downto 0) := "0111111110010010000111111011011";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv31_40490FDB : STD_LOGIC_VECTOR (30 downto 0) := "1000000010010010000111111011011";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";

attribute shreg_extract : string;
    signal c_reg_88 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter10 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter11 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter12 : BOOLEAN;
    signal ap_block_state14_pp0_stage0_iter13 : BOOLEAN;
    signal ap_block_state15_pp0_stage0_iter14 : BOOLEAN;
    signal ap_block_state16_pp0_stage0_iter15 : BOOLEAN;
    signal ap_block_state17_pp0_stage0_iter16 : BOOLEAN;
    signal ap_block_state18_pp0_stage0_iter17 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal grp_atan2_generic_float_s_fu_169_ap_return : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_191 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln757_reg_574 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln757_reg_574_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln757_1_reg_578 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln757_1_reg_578_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_reg_582 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_reg_582_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln766_reg_594 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln766_reg_594_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_2_reg_590 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_2_reg_590_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_reg_598 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_reg_598_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_1_reg_602 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_1_reg_602_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_3_reg_618 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_3_reg_618_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln746_1_reg_622 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln746_1_reg_622_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_fu_201_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_reg_553 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_reg_553_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_reg_553_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_reg_553_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_reg_553_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_reg_553_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_reg_553_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_reg_553_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_reg_553_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_reg_553_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_reg_553_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_reg_553_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_reg_553_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_reg_553_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_reg_553_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_reg_553_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_31_reg_558 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_31_reg_558_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_31_reg_558_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_31_reg_558_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_31_reg_558_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_31_reg_558_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_31_reg_558_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_31_reg_558_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_31_reg_558_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_31_reg_558_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_31_reg_558_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_31_reg_558_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_31_reg_558_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_31_reg_558_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_31_reg_558_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_31_reg_558_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln828_fu_261_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln828_reg_570 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln828_reg_570_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln828_reg_570_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln828_reg_570_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln828_reg_570_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln828_reg_570_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln828_reg_570_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln828_reg_570_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln828_reg_570_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln828_reg_570_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln828_reg_570_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln828_reg_570_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln828_reg_570_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln828_reg_570_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln828_reg_570_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln828_reg_570_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln757_fu_267_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln757_reg_574_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln757_reg_574_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln757_reg_574_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln757_reg_574_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln757_reg_574_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln757_reg_574_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln757_reg_574_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln757_reg_574_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln757_reg_574_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln757_reg_574_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln757_reg_574_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln757_reg_574_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln757_reg_574_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln757_reg_574_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln757_reg_574_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln757_1_fu_291_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln757_1_reg_578_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln757_1_reg_578_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln757_1_reg_578_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln757_1_reg_578_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln757_1_reg_578_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln757_1_reg_578_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln757_1_reg_578_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln757_1_reg_578_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln757_1_reg_578_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln757_1_reg_578_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln757_1_reg_578_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln757_1_reg_578_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln757_1_reg_578_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln757_1_reg_578_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln757_1_reg_578_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_fu_297_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_reg_582_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_reg_582_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_reg_582_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_reg_582_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_reg_582_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_reg_582_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_reg_582_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_reg_582_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_reg_582_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_reg_582_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_reg_582_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_reg_582_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_reg_582_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_reg_582_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_reg_582_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln762_fu_303_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln762_reg_586 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln762_reg_586_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln762_reg_586_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln762_reg_586_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln762_reg_586_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln762_reg_586_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln762_reg_586_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln762_reg_586_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln762_reg_586_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln762_reg_586_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln762_reg_586_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln762_reg_586_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln762_reg_586_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln762_reg_586_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln762_reg_586_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln762_reg_586_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_2_fu_309_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_2_reg_590_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_2_reg_590_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_2_reg_590_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_2_reg_590_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_2_reg_590_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_2_reg_590_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_2_reg_590_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_2_reg_590_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_2_reg_590_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_2_reg_590_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_2_reg_590_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_2_reg_590_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_2_reg_590_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_2_reg_590_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_2_reg_590_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln766_fu_343_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln766_reg_594_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln766_reg_594_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln766_reg_594_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln766_reg_594_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln766_reg_594_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln766_reg_594_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln766_reg_594_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln766_reg_594_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln766_reg_594_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln766_reg_594_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln766_reg_594_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln766_reg_594_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln766_reg_594_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln766_reg_594_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln766_reg_594_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_fu_349_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_reg_598_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_reg_598_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_reg_598_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_reg_598_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_reg_598_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_reg_598_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_reg_598_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_reg_598_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_reg_598_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_reg_598_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_reg_598_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_reg_598_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_reg_598_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_reg_598_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_reg_598_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_1_fu_355_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_1_reg_602_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_1_reg_602_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_1_reg_602_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_1_reg_602_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_1_reg_602_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_1_reg_602_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_1_reg_602_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_1_reg_602_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_1_reg_602_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_1_reg_602_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_1_reg_602_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_1_reg_602_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_1_reg_602_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_1_reg_602_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln18_1_reg_602_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal a_fu_369_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal a_reg_606 : STD_LOGIC_VECTOR (31 downto 0);
    signal b_fu_382_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal b_reg_612 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln824_3_fu_403_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_3_reg_618_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_3_reg_618_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_3_reg_618_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_3_reg_618_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_3_reg_618_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_3_reg_618_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_3_reg_618_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_3_reg_618_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_3_reg_618_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_3_reg_618_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_3_reg_618_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln824_3_reg_618_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln746_1_fu_439_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln746_1_reg_622_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln746_1_reg_622_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln746_1_reg_622_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln746_1_reg_622_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln746_1_reg_622_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln746_1_reg_622_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln746_1_reg_622_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln746_1_reg_622_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln746_1_reg_622_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln746_1_reg_622_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln746_1_reg_622_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln746_1_reg_622_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_175_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_5_fu_445_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_5_reg_631 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_5_reg_631_pp0_iter16_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal bitcast_ln822_1_fu_461_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln809_fu_465_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln351_5_fu_479_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln351_4_fu_490_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln351_3_fu_501_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln351_2_fu_512_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln351_1_fu_523_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln351_fu_534_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_atan2_generic_float_s_fu_169_y_in : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_atan2_generic_float_s_fu_169_x_in : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_atan2_generic_float_s_fu_169_ap_ce : STD_LOGIC;
    signal ap_predicate_op77_call_state2 : BOOLEAN;
    signal ap_predicate_op78_call_state2 : BOOLEAN;
    signal ap_block_state1_pp0_stage0_iter0_ignore_call0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call0 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3_ignore_call0 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4_ignore_call0 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5_ignore_call0 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6_ignore_call0 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7_ignore_call0 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8_ignore_call0 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9_ignore_call0 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter10_ignore_call0 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter11_ignore_call0 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter12_ignore_call0 : BOOLEAN;
    signal ap_block_state14_pp0_stage0_iter13_ignore_call0 : BOOLEAN;
    signal ap_block_state15_pp0_stage0_iter14_ignore_call0 : BOOLEAN;
    signal ap_block_state16_pp0_stage0_iter15_ignore_call0 : BOOLEAN;
    signal ap_block_state17_pp0_stage0_iter16_ignore_call0 : BOOLEAN;
    signal ap_block_state18_pp0_stage0_iter17_ignore_call0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp77 : BOOLEAN;
    signal ap_phi_reg_pp0_iter0_c_reg_88 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter1_c_reg_88 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter2_c_reg_88 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter3_c_reg_88 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter4_c_reg_88 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter5_c_reg_88 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter6_c_reg_88 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter7_c_reg_88 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter8_c_reg_88 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter9_c_reg_88 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter10_c_reg_88 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter11_c_reg_88 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter12_c_reg_88 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter13_c_reg_88 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter14_c_reg_88 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter15_c_reg_88 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_UnifiedRetVal_phi_fu_114_p42 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter0_UnifiedRetVal_reg_102 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter1_UnifiedRetVal_reg_102 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter2_UnifiedRetVal_reg_102 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter3_UnifiedRetVal_reg_102 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter4_UnifiedRetVal_reg_102 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter5_UnifiedRetVal_reg_102 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter6_UnifiedRetVal_reg_102 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter7_UnifiedRetVal_reg_102 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter8_UnifiedRetVal_reg_102 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter9_UnifiedRetVal_reg_102 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter10_UnifiedRetVal_reg_102 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter11_UnifiedRetVal_reg_102 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter12_UnifiedRetVal_reg_102 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter13_UnifiedRetVal_reg_102 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter14_UnifiedRetVal_reg_102 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter15_UnifiedRetVal_reg_102 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter16_UnifiedRetVal_reg_102 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter17_UnifiedRetVal_reg_102 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln826_1_fu_548_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_180_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal tmp_10_fu_187_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_10_fu_187_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal data_V_fu_197_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal data_V_2_fu_223_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_79_fu_235_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln757_fu_249_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_80_fu_245_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal xor_ln18_fu_255_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_209_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln757_1_fu_273_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_78_fu_219_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln828_1_fu_285_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln18_1_fu_279_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln766_fu_315_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_3_fu_325_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal or_ln766_fu_319_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_4_fu_335_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal p_Result_38_fu_361_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln368_fu_365_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_39_fu_374_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln368_1_fu_378_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_40_fu_387_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_41_fu_395_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln746_fu_409_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln746_1_fu_421_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln746_fu_415_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln746_1_fu_427_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln746_fu_433_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_fu_187_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln822_fu_451_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln822_fu_455_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_37_fu_472_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_36_fu_483_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_35_fu_494_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_34_fu_505_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_33_fu_516_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_32_fu_527_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln826_fu_538_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln826_fu_542_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_175_ce : STD_LOGIC;
    signal grp_fu_180_ce : STD_LOGIC;
    signal ap_block_pp0_stage0_00001 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;
    signal y_in_int_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal x_in_int_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_return_int_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_condition_845 : BOOLEAN;
    signal ap_condition_778 : BOOLEAN;
    signal ap_condition_382 : BOOLEAN;
    signal ap_condition_810 : BOOLEAN;
    signal ap_condition_815 : BOOLEAN;
    signal ap_condition_819 : BOOLEAN;
    signal ap_condition_824 : BOOLEAN;
    signal ap_condition_827 : BOOLEAN;
    signal ap_condition_830 : BOOLEAN;
    signal ap_condition_858 : BOOLEAN;
    signal ap_condition_860 : BOOLEAN;
    signal ap_condition_863 : BOOLEAN;
    signal ap_condition_415 : BOOLEAN;
    signal ap_condition_420 : BOOLEAN;
    signal ap_condition_461 : BOOLEAN;
    signal ap_condition_456 : BOOLEAN;
    signal ap_condition_451 : BOOLEAN;
    signal ap_condition_442 : BOOLEAN;
    signal ap_condition_437 : BOOLEAN;
    signal ap_condition_425 : BOOLEAN;
    signal ap_condition_782 : BOOLEAN;

    component apskdemod_atan2_generic_float_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        y_in : IN STD_LOGIC_VECTOR (31 downto 0);
        x_in : IN STD_LOGIC_VECTOR (31 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_ce : IN STD_LOGIC );
    end component;


    component apskdemod_fsub_32ns_32ns_32_3_full_dsp_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component apskdemod_fcmp_32ns_32ns_1_1_no_dsp_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    grp_atan2_generic_float_s_fu_169 : component apskdemod_atan2_generic_float_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        y_in => grp_atan2_generic_float_s_fu_169_y_in,
        x_in => grp_atan2_generic_float_s_fu_169_x_in,
        ap_return => grp_atan2_generic_float_s_fu_169_ap_return,
        ap_ce => grp_atan2_generic_float_s_fu_169_ap_ce);

    fsub_32ns_32ns_32_3_full_dsp_0_U57 : component apskdemod_fsub_32ns_32ns_32_3_full_dsp_0
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => ap_const_lv32_3FC90FDB,
        din1 => reg_191,
        ce => grp_fu_175_ce,
        dout => grp_fu_175_p2);

    fsub_32ns_32ns_32_3_full_dsp_0_U58 : component apskdemod_fsub_32ns_32ns_32_3_full_dsp_0
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => ap_const_lv32_40490FDB,
        din1 => ap_phi_reg_pp0_iter15_c_reg_88,
        ce => grp_fu_180_ce,
        dout => grp_fu_180_p2);

    fcmp_32ns_32ns_1_1_no_dsp_0_U59 : component apskdemod_fcmp_32ns_32ns_1_1_no_dsp_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 1)
    port map (
        din0 => tmp_10_fu_187_p0,
        din1 => tmp_10_fu_187_p1,
        opcode => ap_const_lv5_2,
        dout => tmp_10_fu_187_p2);





    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;

    ap_phi_reg_pp0_iter13_c_reg_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                if ((ap_const_boolean_1 = ap_condition_778)) then 
                    ap_phi_reg_pp0_iter13_c_reg_88 <= reg_191;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter13_c_reg_88 <= ap_phi_reg_pp0_iter12_c_reg_88;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter15_c_reg_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                if ((ap_const_boolean_1 = ap_condition_382)) then 
                    ap_phi_reg_pp0_iter15_c_reg_88 <= grp_fu_175_p2;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter15_c_reg_88 <= ap_phi_reg_pp0_iter14_c_reg_88;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter16_UnifiedRetVal_reg_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                if ((ap_const_boolean_1 = ap_condition_863)) then 
                    ap_phi_reg_pp0_iter16_UnifiedRetVal_reg_102 <= ap_const_lv32_0;
                elsif ((ap_const_boolean_1 = ap_condition_860)) then 
                    ap_phi_reg_pp0_iter16_UnifiedRetVal_reg_102 <= ap_const_lv32_3F490FDB;
                elsif ((ap_const_boolean_1 = ap_condition_858)) then 
                    ap_phi_reg_pp0_iter16_UnifiedRetVal_reg_102 <= ap_phi_reg_pp0_iter15_c_reg_88;
                elsif ((ap_const_boolean_1 = ap_condition_830)) then 
                    ap_phi_reg_pp0_iter16_UnifiedRetVal_reg_102 <= ap_const_lv32_80000000;
                elsif ((ap_const_boolean_1 = ap_condition_827)) then 
                    ap_phi_reg_pp0_iter16_UnifiedRetVal_reg_102 <= ap_const_lv32_40490FDB;
                elsif ((ap_const_boolean_1 = ap_condition_824)) then 
                    ap_phi_reg_pp0_iter16_UnifiedRetVal_reg_102 <= ap_const_lv32_C0490FDB;
                elsif ((ap_const_boolean_1 = ap_condition_819)) then 
                    ap_phi_reg_pp0_iter16_UnifiedRetVal_reg_102 <= ap_const_lv32_BF490FDB;
                elsif ((ap_const_boolean_1 = ap_condition_815)) then 
                    ap_phi_reg_pp0_iter16_UnifiedRetVal_reg_102 <= ap_const_lv32_4016CBE4;
                elsif ((ap_const_boolean_1 = ap_condition_810)) then 
                    ap_phi_reg_pp0_iter16_UnifiedRetVal_reg_102 <= ap_const_lv32_C016CBE4;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter16_UnifiedRetVal_reg_102 <= ap_phi_reg_pp0_iter15_UnifiedRetVal_reg_102;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter17_UnifiedRetVal_reg_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                if ((ap_const_boolean_1 = ap_condition_425)) then 
                    ap_phi_reg_pp0_iter17_UnifiedRetVal_reg_102 <= bitcast_ln351_5_fu_479_p1;
                elsif ((ap_const_boolean_1 = ap_condition_437)) then 
                    ap_phi_reg_pp0_iter17_UnifiedRetVal_reg_102 <= bitcast_ln351_4_fu_490_p1;
                elsif ((ap_const_boolean_1 = ap_condition_442)) then 
                    ap_phi_reg_pp0_iter17_UnifiedRetVal_reg_102 <= bitcast_ln351_3_fu_501_p1;
                elsif ((ap_const_boolean_1 = ap_condition_451)) then 
                    ap_phi_reg_pp0_iter17_UnifiedRetVal_reg_102 <= bitcast_ln351_2_fu_512_p1;
                elsif ((ap_const_boolean_1 = ap_condition_456)) then 
                    ap_phi_reg_pp0_iter17_UnifiedRetVal_reg_102 <= bitcast_ln351_1_fu_523_p1;
                elsif ((ap_const_boolean_1 = ap_condition_461)) then 
                    ap_phi_reg_pp0_iter17_UnifiedRetVal_reg_102 <= bitcast_ln351_fu_534_p1;
                elsif ((ap_const_boolean_1 = ap_condition_420)) then 
                    ap_phi_reg_pp0_iter17_UnifiedRetVal_reg_102 <= select_ln809_fu_465_p3;
                elsif ((ap_const_boolean_1 = ap_condition_415)) then 
                    ap_phi_reg_pp0_iter17_UnifiedRetVal_reg_102 <= bitcast_ln822_1_fu_461_p1;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter17_UnifiedRetVal_reg_102 <= ap_phi_reg_pp0_iter16_UnifiedRetVal_reg_102;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_UnifiedRetVal_reg_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (or_ln757_1_fu_291_p2 = ap_const_lv1_0) and (or_ln757_fu_267_p2 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (or_ln757_fu_267_p2 = ap_const_lv1_0)))) then 
                ap_phi_reg_pp0_iter1_UnifiedRetVal_reg_102 <= ap_const_lv32_7FFFFFFF;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
                ap_phi_reg_pp0_iter1_UnifiedRetVal_reg_102 <= ap_phi_reg_pp0_iter0_UnifiedRetVal_reg_102;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_c_reg_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                if ((ap_const_boolean_1 = ap_condition_782)) then 
                    ap_phi_reg_pp0_iter1_c_reg_88 <= ap_const_lv32_3F490FDB;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_c_reg_88 <= ap_phi_reg_pp0_iter0_c_reg_88;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_0 = and_ln18_1_fu_355_p2) and (ap_const_lv1_0 = and_ln18_fu_349_p2) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln766_fu_343_p2 = ap_const_lv1_0) and (icmp_ln824_2_fu_309_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_ce_reg) and (icmp_ln824_fu_297_p2 = ap_const_lv1_0) and (or_ln757_1_fu_291_p2 = ap_const_lv1_1) and (or_ln757_fu_267_p2 = ap_const_lv1_1))) then
                    a_reg_606(30 downto 0) <= a_fu_369_p1(30 downto 0);
                    b_reg_612(30 downto 0) <= b_fu_382_p1(30 downto 0);
                icmp_ln824_3_reg_618 <= icmp_ln824_3_fu_403_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln766_fu_343_p2 = ap_const_lv1_0) and (icmp_ln824_2_fu_309_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_ce_reg) and (icmp_ln824_fu_297_p2 = ap_const_lv1_0) and (or_ln757_1_fu_291_p2 = ap_const_lv1_1) and (or_ln757_fu_267_p2 = ap_const_lv1_1))) then
                and_ln18_1_reg_602 <= and_ln18_1_fu_355_p2;
                and_ln18_reg_598 <= and_ln18_fu_349_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                and_ln18_1_reg_602_pp0_iter10_reg <= and_ln18_1_reg_602_pp0_iter9_reg;
                and_ln18_1_reg_602_pp0_iter11_reg <= and_ln18_1_reg_602_pp0_iter10_reg;
                and_ln18_1_reg_602_pp0_iter12_reg <= and_ln18_1_reg_602_pp0_iter11_reg;
                and_ln18_1_reg_602_pp0_iter13_reg <= and_ln18_1_reg_602_pp0_iter12_reg;
                and_ln18_1_reg_602_pp0_iter14_reg <= and_ln18_1_reg_602_pp0_iter13_reg;
                and_ln18_1_reg_602_pp0_iter15_reg <= and_ln18_1_reg_602_pp0_iter14_reg;
                and_ln18_1_reg_602_pp0_iter16_reg <= and_ln18_1_reg_602_pp0_iter15_reg;
                and_ln18_1_reg_602_pp0_iter1_reg <= and_ln18_1_reg_602;
                and_ln18_1_reg_602_pp0_iter2_reg <= and_ln18_1_reg_602_pp0_iter1_reg;
                and_ln18_1_reg_602_pp0_iter3_reg <= and_ln18_1_reg_602_pp0_iter2_reg;
                and_ln18_1_reg_602_pp0_iter4_reg <= and_ln18_1_reg_602_pp0_iter3_reg;
                and_ln18_1_reg_602_pp0_iter5_reg <= and_ln18_1_reg_602_pp0_iter4_reg;
                and_ln18_1_reg_602_pp0_iter6_reg <= and_ln18_1_reg_602_pp0_iter5_reg;
                and_ln18_1_reg_602_pp0_iter7_reg <= and_ln18_1_reg_602_pp0_iter6_reg;
                and_ln18_1_reg_602_pp0_iter8_reg <= and_ln18_1_reg_602_pp0_iter7_reg;
                and_ln18_1_reg_602_pp0_iter9_reg <= and_ln18_1_reg_602_pp0_iter8_reg;
                and_ln18_reg_598_pp0_iter10_reg <= and_ln18_reg_598_pp0_iter9_reg;
                and_ln18_reg_598_pp0_iter11_reg <= and_ln18_reg_598_pp0_iter10_reg;
                and_ln18_reg_598_pp0_iter12_reg <= and_ln18_reg_598_pp0_iter11_reg;
                and_ln18_reg_598_pp0_iter13_reg <= and_ln18_reg_598_pp0_iter12_reg;
                and_ln18_reg_598_pp0_iter14_reg <= and_ln18_reg_598_pp0_iter13_reg;
                and_ln18_reg_598_pp0_iter15_reg <= and_ln18_reg_598_pp0_iter14_reg;
                and_ln18_reg_598_pp0_iter16_reg <= and_ln18_reg_598_pp0_iter15_reg;
                and_ln18_reg_598_pp0_iter1_reg <= and_ln18_reg_598;
                and_ln18_reg_598_pp0_iter2_reg <= and_ln18_reg_598_pp0_iter1_reg;
                and_ln18_reg_598_pp0_iter3_reg <= and_ln18_reg_598_pp0_iter2_reg;
                and_ln18_reg_598_pp0_iter4_reg <= and_ln18_reg_598_pp0_iter3_reg;
                and_ln18_reg_598_pp0_iter5_reg <= and_ln18_reg_598_pp0_iter4_reg;
                and_ln18_reg_598_pp0_iter6_reg <= and_ln18_reg_598_pp0_iter5_reg;
                and_ln18_reg_598_pp0_iter7_reg <= and_ln18_reg_598_pp0_iter6_reg;
                and_ln18_reg_598_pp0_iter8_reg <= and_ln18_reg_598_pp0_iter7_reg;
                and_ln18_reg_598_pp0_iter9_reg <= and_ln18_reg_598_pp0_iter8_reg;
                and_ln746_1_reg_622_pp0_iter10_reg <= and_ln746_1_reg_622_pp0_iter9_reg;
                and_ln746_1_reg_622_pp0_iter11_reg <= and_ln746_1_reg_622_pp0_iter10_reg;
                and_ln746_1_reg_622_pp0_iter12_reg <= and_ln746_1_reg_622_pp0_iter11_reg;
                and_ln746_1_reg_622_pp0_iter13_reg <= and_ln746_1_reg_622_pp0_iter12_reg;
                and_ln746_1_reg_622_pp0_iter1_reg <= and_ln746_1_reg_622;
                and_ln746_1_reg_622_pp0_iter2_reg <= and_ln746_1_reg_622_pp0_iter1_reg;
                and_ln746_1_reg_622_pp0_iter3_reg <= and_ln746_1_reg_622_pp0_iter2_reg;
                and_ln746_1_reg_622_pp0_iter4_reg <= and_ln746_1_reg_622_pp0_iter3_reg;
                and_ln746_1_reg_622_pp0_iter5_reg <= and_ln746_1_reg_622_pp0_iter4_reg;
                and_ln746_1_reg_622_pp0_iter6_reg <= and_ln746_1_reg_622_pp0_iter5_reg;
                and_ln746_1_reg_622_pp0_iter7_reg <= and_ln746_1_reg_622_pp0_iter6_reg;
                and_ln746_1_reg_622_pp0_iter8_reg <= and_ln746_1_reg_622_pp0_iter7_reg;
                and_ln746_1_reg_622_pp0_iter9_reg <= and_ln746_1_reg_622_pp0_iter8_reg;
                and_ln762_reg_586_pp0_iter10_reg <= and_ln762_reg_586_pp0_iter9_reg;
                and_ln762_reg_586_pp0_iter11_reg <= and_ln762_reg_586_pp0_iter10_reg;
                and_ln762_reg_586_pp0_iter12_reg <= and_ln762_reg_586_pp0_iter11_reg;
                and_ln762_reg_586_pp0_iter13_reg <= and_ln762_reg_586_pp0_iter12_reg;
                and_ln762_reg_586_pp0_iter14_reg <= and_ln762_reg_586_pp0_iter13_reg;
                and_ln762_reg_586_pp0_iter15_reg <= and_ln762_reg_586_pp0_iter14_reg;
                and_ln762_reg_586_pp0_iter1_reg <= and_ln762_reg_586;
                and_ln762_reg_586_pp0_iter2_reg <= and_ln762_reg_586_pp0_iter1_reg;
                and_ln762_reg_586_pp0_iter3_reg <= and_ln762_reg_586_pp0_iter2_reg;
                and_ln762_reg_586_pp0_iter4_reg <= and_ln762_reg_586_pp0_iter3_reg;
                and_ln762_reg_586_pp0_iter5_reg <= and_ln762_reg_586_pp0_iter4_reg;
                and_ln762_reg_586_pp0_iter6_reg <= and_ln762_reg_586_pp0_iter5_reg;
                and_ln762_reg_586_pp0_iter7_reg <= and_ln762_reg_586_pp0_iter6_reg;
                and_ln762_reg_586_pp0_iter8_reg <= and_ln762_reg_586_pp0_iter7_reg;
                and_ln762_reg_586_pp0_iter9_reg <= and_ln762_reg_586_pp0_iter8_reg;
                ap_phi_reg_pp0_iter10_UnifiedRetVal_reg_102 <= ap_phi_reg_pp0_iter9_UnifiedRetVal_reg_102;
                ap_phi_reg_pp0_iter10_c_reg_88 <= ap_phi_reg_pp0_iter9_c_reg_88;
                ap_phi_reg_pp0_iter11_UnifiedRetVal_reg_102 <= ap_phi_reg_pp0_iter10_UnifiedRetVal_reg_102;
                ap_phi_reg_pp0_iter11_c_reg_88 <= ap_phi_reg_pp0_iter10_c_reg_88;
                ap_phi_reg_pp0_iter12_UnifiedRetVal_reg_102 <= ap_phi_reg_pp0_iter11_UnifiedRetVal_reg_102;
                ap_phi_reg_pp0_iter12_c_reg_88 <= ap_phi_reg_pp0_iter11_c_reg_88;
                ap_phi_reg_pp0_iter13_UnifiedRetVal_reg_102 <= ap_phi_reg_pp0_iter12_UnifiedRetVal_reg_102;
                ap_phi_reg_pp0_iter14_UnifiedRetVal_reg_102 <= ap_phi_reg_pp0_iter13_UnifiedRetVal_reg_102;
                ap_phi_reg_pp0_iter14_c_reg_88 <= ap_phi_reg_pp0_iter13_c_reg_88;
                ap_phi_reg_pp0_iter15_UnifiedRetVal_reg_102 <= ap_phi_reg_pp0_iter14_UnifiedRetVal_reg_102;
                ap_phi_reg_pp0_iter2_UnifiedRetVal_reg_102 <= ap_phi_reg_pp0_iter1_UnifiedRetVal_reg_102;
                ap_phi_reg_pp0_iter2_c_reg_88 <= ap_phi_reg_pp0_iter1_c_reg_88;
                ap_phi_reg_pp0_iter3_UnifiedRetVal_reg_102 <= ap_phi_reg_pp0_iter2_UnifiedRetVal_reg_102;
                ap_phi_reg_pp0_iter3_c_reg_88 <= ap_phi_reg_pp0_iter2_c_reg_88;
                ap_phi_reg_pp0_iter4_UnifiedRetVal_reg_102 <= ap_phi_reg_pp0_iter3_UnifiedRetVal_reg_102;
                ap_phi_reg_pp0_iter4_c_reg_88 <= ap_phi_reg_pp0_iter3_c_reg_88;
                ap_phi_reg_pp0_iter5_UnifiedRetVal_reg_102 <= ap_phi_reg_pp0_iter4_UnifiedRetVal_reg_102;
                ap_phi_reg_pp0_iter5_c_reg_88 <= ap_phi_reg_pp0_iter4_c_reg_88;
                ap_phi_reg_pp0_iter6_UnifiedRetVal_reg_102 <= ap_phi_reg_pp0_iter5_UnifiedRetVal_reg_102;
                ap_phi_reg_pp0_iter6_c_reg_88 <= ap_phi_reg_pp0_iter5_c_reg_88;
                ap_phi_reg_pp0_iter7_UnifiedRetVal_reg_102 <= ap_phi_reg_pp0_iter6_UnifiedRetVal_reg_102;
                ap_phi_reg_pp0_iter7_c_reg_88 <= ap_phi_reg_pp0_iter6_c_reg_88;
                ap_phi_reg_pp0_iter8_UnifiedRetVal_reg_102 <= ap_phi_reg_pp0_iter7_UnifiedRetVal_reg_102;
                ap_phi_reg_pp0_iter8_c_reg_88 <= ap_phi_reg_pp0_iter7_c_reg_88;
                ap_phi_reg_pp0_iter9_UnifiedRetVal_reg_102 <= ap_phi_reg_pp0_iter8_UnifiedRetVal_reg_102;
                ap_phi_reg_pp0_iter9_c_reg_88 <= ap_phi_reg_pp0_iter8_c_reg_88;
                c_reg_88 <= ap_phi_reg_pp0_iter15_c_reg_88;
                icmp_ln766_reg_594_pp0_iter10_reg <= icmp_ln766_reg_594_pp0_iter9_reg;
                icmp_ln766_reg_594_pp0_iter11_reg <= icmp_ln766_reg_594_pp0_iter10_reg;
                icmp_ln766_reg_594_pp0_iter12_reg <= icmp_ln766_reg_594_pp0_iter11_reg;
                icmp_ln766_reg_594_pp0_iter13_reg <= icmp_ln766_reg_594_pp0_iter12_reg;
                icmp_ln766_reg_594_pp0_iter14_reg <= icmp_ln766_reg_594_pp0_iter13_reg;
                icmp_ln766_reg_594_pp0_iter15_reg <= icmp_ln766_reg_594_pp0_iter14_reg;
                icmp_ln766_reg_594_pp0_iter16_reg <= icmp_ln766_reg_594_pp0_iter15_reg;
                icmp_ln766_reg_594_pp0_iter1_reg <= icmp_ln766_reg_594;
                icmp_ln766_reg_594_pp0_iter2_reg <= icmp_ln766_reg_594_pp0_iter1_reg;
                icmp_ln766_reg_594_pp0_iter3_reg <= icmp_ln766_reg_594_pp0_iter2_reg;
                icmp_ln766_reg_594_pp0_iter4_reg <= icmp_ln766_reg_594_pp0_iter3_reg;
                icmp_ln766_reg_594_pp0_iter5_reg <= icmp_ln766_reg_594_pp0_iter4_reg;
                icmp_ln766_reg_594_pp0_iter6_reg <= icmp_ln766_reg_594_pp0_iter5_reg;
                icmp_ln766_reg_594_pp0_iter7_reg <= icmp_ln766_reg_594_pp0_iter6_reg;
                icmp_ln766_reg_594_pp0_iter8_reg <= icmp_ln766_reg_594_pp0_iter7_reg;
                icmp_ln766_reg_594_pp0_iter9_reg <= icmp_ln766_reg_594_pp0_iter8_reg;
                icmp_ln824_2_reg_590_pp0_iter10_reg <= icmp_ln824_2_reg_590_pp0_iter9_reg;
                icmp_ln824_2_reg_590_pp0_iter11_reg <= icmp_ln824_2_reg_590_pp0_iter10_reg;
                icmp_ln824_2_reg_590_pp0_iter12_reg <= icmp_ln824_2_reg_590_pp0_iter11_reg;
                icmp_ln824_2_reg_590_pp0_iter13_reg <= icmp_ln824_2_reg_590_pp0_iter12_reg;
                icmp_ln824_2_reg_590_pp0_iter14_reg <= icmp_ln824_2_reg_590_pp0_iter13_reg;
                icmp_ln824_2_reg_590_pp0_iter15_reg <= icmp_ln824_2_reg_590_pp0_iter14_reg;
                icmp_ln824_2_reg_590_pp0_iter16_reg <= icmp_ln824_2_reg_590_pp0_iter15_reg;
                icmp_ln824_2_reg_590_pp0_iter1_reg <= icmp_ln824_2_reg_590;
                icmp_ln824_2_reg_590_pp0_iter2_reg <= icmp_ln824_2_reg_590_pp0_iter1_reg;
                icmp_ln824_2_reg_590_pp0_iter3_reg <= icmp_ln824_2_reg_590_pp0_iter2_reg;
                icmp_ln824_2_reg_590_pp0_iter4_reg <= icmp_ln824_2_reg_590_pp0_iter3_reg;
                icmp_ln824_2_reg_590_pp0_iter5_reg <= icmp_ln824_2_reg_590_pp0_iter4_reg;
                icmp_ln824_2_reg_590_pp0_iter6_reg <= icmp_ln824_2_reg_590_pp0_iter5_reg;
                icmp_ln824_2_reg_590_pp0_iter7_reg <= icmp_ln824_2_reg_590_pp0_iter6_reg;
                icmp_ln824_2_reg_590_pp0_iter8_reg <= icmp_ln824_2_reg_590_pp0_iter7_reg;
                icmp_ln824_2_reg_590_pp0_iter9_reg <= icmp_ln824_2_reg_590_pp0_iter8_reg;
                icmp_ln824_3_reg_618_pp0_iter10_reg <= icmp_ln824_3_reg_618_pp0_iter9_reg;
                icmp_ln824_3_reg_618_pp0_iter11_reg <= icmp_ln824_3_reg_618_pp0_iter10_reg;
                icmp_ln824_3_reg_618_pp0_iter12_reg <= icmp_ln824_3_reg_618_pp0_iter11_reg;
                icmp_ln824_3_reg_618_pp0_iter13_reg <= icmp_ln824_3_reg_618_pp0_iter12_reg;
                icmp_ln824_3_reg_618_pp0_iter1_reg <= icmp_ln824_3_reg_618;
                icmp_ln824_3_reg_618_pp0_iter2_reg <= icmp_ln824_3_reg_618_pp0_iter1_reg;
                icmp_ln824_3_reg_618_pp0_iter3_reg <= icmp_ln824_3_reg_618_pp0_iter2_reg;
                icmp_ln824_3_reg_618_pp0_iter4_reg <= icmp_ln824_3_reg_618_pp0_iter3_reg;
                icmp_ln824_3_reg_618_pp0_iter5_reg <= icmp_ln824_3_reg_618_pp0_iter4_reg;
                icmp_ln824_3_reg_618_pp0_iter6_reg <= icmp_ln824_3_reg_618_pp0_iter5_reg;
                icmp_ln824_3_reg_618_pp0_iter7_reg <= icmp_ln824_3_reg_618_pp0_iter6_reg;
                icmp_ln824_3_reg_618_pp0_iter8_reg <= icmp_ln824_3_reg_618_pp0_iter7_reg;
                icmp_ln824_3_reg_618_pp0_iter9_reg <= icmp_ln824_3_reg_618_pp0_iter8_reg;
                icmp_ln824_reg_582_pp0_iter10_reg <= icmp_ln824_reg_582_pp0_iter9_reg;
                icmp_ln824_reg_582_pp0_iter11_reg <= icmp_ln824_reg_582_pp0_iter10_reg;
                icmp_ln824_reg_582_pp0_iter12_reg <= icmp_ln824_reg_582_pp0_iter11_reg;
                icmp_ln824_reg_582_pp0_iter13_reg <= icmp_ln824_reg_582_pp0_iter12_reg;
                icmp_ln824_reg_582_pp0_iter14_reg <= icmp_ln824_reg_582_pp0_iter13_reg;
                icmp_ln824_reg_582_pp0_iter15_reg <= icmp_ln824_reg_582_pp0_iter14_reg;
                icmp_ln824_reg_582_pp0_iter16_reg <= icmp_ln824_reg_582_pp0_iter15_reg;
                icmp_ln824_reg_582_pp0_iter1_reg <= icmp_ln824_reg_582;
                icmp_ln824_reg_582_pp0_iter2_reg <= icmp_ln824_reg_582_pp0_iter1_reg;
                icmp_ln824_reg_582_pp0_iter3_reg <= icmp_ln824_reg_582_pp0_iter2_reg;
                icmp_ln824_reg_582_pp0_iter4_reg <= icmp_ln824_reg_582_pp0_iter3_reg;
                icmp_ln824_reg_582_pp0_iter5_reg <= icmp_ln824_reg_582_pp0_iter4_reg;
                icmp_ln824_reg_582_pp0_iter6_reg <= icmp_ln824_reg_582_pp0_iter5_reg;
                icmp_ln824_reg_582_pp0_iter7_reg <= icmp_ln824_reg_582_pp0_iter6_reg;
                icmp_ln824_reg_582_pp0_iter8_reg <= icmp_ln824_reg_582_pp0_iter7_reg;
                icmp_ln824_reg_582_pp0_iter9_reg <= icmp_ln824_reg_582_pp0_iter8_reg;
                icmp_ln828_reg_570 <= icmp_ln828_fu_261_p2;
                icmp_ln828_reg_570_pp0_iter10_reg <= icmp_ln828_reg_570_pp0_iter9_reg;
                icmp_ln828_reg_570_pp0_iter11_reg <= icmp_ln828_reg_570_pp0_iter10_reg;
                icmp_ln828_reg_570_pp0_iter12_reg <= icmp_ln828_reg_570_pp0_iter11_reg;
                icmp_ln828_reg_570_pp0_iter13_reg <= icmp_ln828_reg_570_pp0_iter12_reg;
                icmp_ln828_reg_570_pp0_iter14_reg <= icmp_ln828_reg_570_pp0_iter13_reg;
                icmp_ln828_reg_570_pp0_iter15_reg <= icmp_ln828_reg_570_pp0_iter14_reg;
                icmp_ln828_reg_570_pp0_iter1_reg <= icmp_ln828_reg_570;
                icmp_ln828_reg_570_pp0_iter2_reg <= icmp_ln828_reg_570_pp0_iter1_reg;
                icmp_ln828_reg_570_pp0_iter3_reg <= icmp_ln828_reg_570_pp0_iter2_reg;
                icmp_ln828_reg_570_pp0_iter4_reg <= icmp_ln828_reg_570_pp0_iter3_reg;
                icmp_ln828_reg_570_pp0_iter5_reg <= icmp_ln828_reg_570_pp0_iter4_reg;
                icmp_ln828_reg_570_pp0_iter6_reg <= icmp_ln828_reg_570_pp0_iter5_reg;
                icmp_ln828_reg_570_pp0_iter7_reg <= icmp_ln828_reg_570_pp0_iter6_reg;
                icmp_ln828_reg_570_pp0_iter8_reg <= icmp_ln828_reg_570_pp0_iter7_reg;
                icmp_ln828_reg_570_pp0_iter9_reg <= icmp_ln828_reg_570_pp0_iter8_reg;
                or_ln757_1_reg_578_pp0_iter10_reg <= or_ln757_1_reg_578_pp0_iter9_reg;
                or_ln757_1_reg_578_pp0_iter11_reg <= or_ln757_1_reg_578_pp0_iter10_reg;
                or_ln757_1_reg_578_pp0_iter12_reg <= or_ln757_1_reg_578_pp0_iter11_reg;
                or_ln757_1_reg_578_pp0_iter13_reg <= or_ln757_1_reg_578_pp0_iter12_reg;
                or_ln757_1_reg_578_pp0_iter14_reg <= or_ln757_1_reg_578_pp0_iter13_reg;
                or_ln757_1_reg_578_pp0_iter15_reg <= or_ln757_1_reg_578_pp0_iter14_reg;
                or_ln757_1_reg_578_pp0_iter16_reg <= or_ln757_1_reg_578_pp0_iter15_reg;
                or_ln757_1_reg_578_pp0_iter1_reg <= or_ln757_1_reg_578;
                or_ln757_1_reg_578_pp0_iter2_reg <= or_ln757_1_reg_578_pp0_iter1_reg;
                or_ln757_1_reg_578_pp0_iter3_reg <= or_ln757_1_reg_578_pp0_iter2_reg;
                or_ln757_1_reg_578_pp0_iter4_reg <= or_ln757_1_reg_578_pp0_iter3_reg;
                or_ln757_1_reg_578_pp0_iter5_reg <= or_ln757_1_reg_578_pp0_iter4_reg;
                or_ln757_1_reg_578_pp0_iter6_reg <= or_ln757_1_reg_578_pp0_iter5_reg;
                or_ln757_1_reg_578_pp0_iter7_reg <= or_ln757_1_reg_578_pp0_iter6_reg;
                or_ln757_1_reg_578_pp0_iter8_reg <= or_ln757_1_reg_578_pp0_iter7_reg;
                or_ln757_1_reg_578_pp0_iter9_reg <= or_ln757_1_reg_578_pp0_iter8_reg;
                or_ln757_reg_574 <= or_ln757_fu_267_p2;
                or_ln757_reg_574_pp0_iter10_reg <= or_ln757_reg_574_pp0_iter9_reg;
                or_ln757_reg_574_pp0_iter11_reg <= or_ln757_reg_574_pp0_iter10_reg;
                or_ln757_reg_574_pp0_iter12_reg <= or_ln757_reg_574_pp0_iter11_reg;
                or_ln757_reg_574_pp0_iter13_reg <= or_ln757_reg_574_pp0_iter12_reg;
                or_ln757_reg_574_pp0_iter14_reg <= or_ln757_reg_574_pp0_iter13_reg;
                or_ln757_reg_574_pp0_iter15_reg <= or_ln757_reg_574_pp0_iter14_reg;
                or_ln757_reg_574_pp0_iter16_reg <= or_ln757_reg_574_pp0_iter15_reg;
                or_ln757_reg_574_pp0_iter1_reg <= or_ln757_reg_574;
                or_ln757_reg_574_pp0_iter2_reg <= or_ln757_reg_574_pp0_iter1_reg;
                or_ln757_reg_574_pp0_iter3_reg <= or_ln757_reg_574_pp0_iter2_reg;
                or_ln757_reg_574_pp0_iter4_reg <= or_ln757_reg_574_pp0_iter3_reg;
                or_ln757_reg_574_pp0_iter5_reg <= or_ln757_reg_574_pp0_iter4_reg;
                or_ln757_reg_574_pp0_iter6_reg <= or_ln757_reg_574_pp0_iter5_reg;
                or_ln757_reg_574_pp0_iter7_reg <= or_ln757_reg_574_pp0_iter6_reg;
                or_ln757_reg_574_pp0_iter8_reg <= or_ln757_reg_574_pp0_iter7_reg;
                or_ln757_reg_574_pp0_iter9_reg <= or_ln757_reg_574_pp0_iter8_reg;
                p_Result_31_reg_558 <= data_V_2_fu_223_p1(31 downto 31);
                p_Result_31_reg_558_pp0_iter10_reg <= p_Result_31_reg_558_pp0_iter9_reg;
                p_Result_31_reg_558_pp0_iter11_reg <= p_Result_31_reg_558_pp0_iter10_reg;
                p_Result_31_reg_558_pp0_iter12_reg <= p_Result_31_reg_558_pp0_iter11_reg;
                p_Result_31_reg_558_pp0_iter13_reg <= p_Result_31_reg_558_pp0_iter12_reg;
                p_Result_31_reg_558_pp0_iter14_reg <= p_Result_31_reg_558_pp0_iter13_reg;
                p_Result_31_reg_558_pp0_iter15_reg <= p_Result_31_reg_558_pp0_iter14_reg;
                p_Result_31_reg_558_pp0_iter1_reg <= p_Result_31_reg_558;
                p_Result_31_reg_558_pp0_iter2_reg <= p_Result_31_reg_558_pp0_iter1_reg;
                p_Result_31_reg_558_pp0_iter3_reg <= p_Result_31_reg_558_pp0_iter2_reg;
                p_Result_31_reg_558_pp0_iter4_reg <= p_Result_31_reg_558_pp0_iter3_reg;
                p_Result_31_reg_558_pp0_iter5_reg <= p_Result_31_reg_558_pp0_iter4_reg;
                p_Result_31_reg_558_pp0_iter6_reg <= p_Result_31_reg_558_pp0_iter5_reg;
                p_Result_31_reg_558_pp0_iter7_reg <= p_Result_31_reg_558_pp0_iter6_reg;
                p_Result_31_reg_558_pp0_iter8_reg <= p_Result_31_reg_558_pp0_iter7_reg;
                p_Result_31_reg_558_pp0_iter9_reg <= p_Result_31_reg_558_pp0_iter8_reg;
                p_Result_s_reg_553 <= data_V_fu_197_p1(31 downto 31);
                p_Result_s_reg_553_pp0_iter10_reg <= p_Result_s_reg_553_pp0_iter9_reg;
                p_Result_s_reg_553_pp0_iter11_reg <= p_Result_s_reg_553_pp0_iter10_reg;
                p_Result_s_reg_553_pp0_iter12_reg <= p_Result_s_reg_553_pp0_iter11_reg;
                p_Result_s_reg_553_pp0_iter13_reg <= p_Result_s_reg_553_pp0_iter12_reg;
                p_Result_s_reg_553_pp0_iter14_reg <= p_Result_s_reg_553_pp0_iter13_reg;
                p_Result_s_reg_553_pp0_iter15_reg <= p_Result_s_reg_553_pp0_iter14_reg;
                p_Result_s_reg_553_pp0_iter1_reg <= p_Result_s_reg_553;
                p_Result_s_reg_553_pp0_iter2_reg <= p_Result_s_reg_553_pp0_iter1_reg;
                p_Result_s_reg_553_pp0_iter3_reg <= p_Result_s_reg_553_pp0_iter2_reg;
                p_Result_s_reg_553_pp0_iter4_reg <= p_Result_s_reg_553_pp0_iter3_reg;
                p_Result_s_reg_553_pp0_iter5_reg <= p_Result_s_reg_553_pp0_iter4_reg;
                p_Result_s_reg_553_pp0_iter6_reg <= p_Result_s_reg_553_pp0_iter5_reg;
                p_Result_s_reg_553_pp0_iter7_reg <= p_Result_s_reg_553_pp0_iter6_reg;
                p_Result_s_reg_553_pp0_iter8_reg <= p_Result_s_reg_553_pp0_iter7_reg;
                p_Result_s_reg_553_pp0_iter9_reg <= p_Result_s_reg_553_pp0_iter8_reg;
                tmp_5_reg_631_pp0_iter16_reg <= tmp_5_reg_631;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_0 = and_ln18_1_fu_355_p2) and (ap_const_lv1_0 = and_ln18_fu_349_p2) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln824_3_fu_403_p2 = ap_const_lv1_0) and (icmp_ln766_fu_343_p2 = ap_const_lv1_0) and (icmp_ln824_2_fu_309_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_ce_reg) and (icmp_ln824_fu_297_p2 = ap_const_lv1_0) and (or_ln757_1_fu_291_p2 = ap_const_lv1_1) and (or_ln757_fu_267_p2 = ap_const_lv1_1))) then
                and_ln746_1_reg_622 <= and_ln746_1_fu_439_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (icmp_ln824_fu_297_p2 = ap_const_lv1_1) and (or_ln757_1_fu_291_p2 = ap_const_lv1_1) and (or_ln757_fu_267_p2 = ap_const_lv1_1))) then
                and_ln762_reg_586 <= and_ln762_fu_303_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_int_reg <= ap_phi_mux_UnifiedRetVal_phi_fu_114_p42;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (((icmp_ln824_fu_297_p2 = ap_const_lv1_0) and (or_ln757_1_fu_291_p2 = ap_const_lv1_1) and (or_ln757_fu_267_p2 = ap_const_lv1_1)) or ((ap_const_lv1_0 = and_ln762_fu_303_p2) and (or_ln757_1_fu_291_p2 = ap_const_lv1_1) and (or_ln757_fu_267_p2 = ap_const_lv1_1) and (icmp_ln828_fu_261_p2 = ap_const_lv1_0))))) then
                icmp_ln766_reg_594 <= icmp_ln766_fu_343_p2;
                icmp_ln824_2_reg_590 <= icmp_ln824_2_fu_309_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (or_ln757_1_fu_291_p2 = ap_const_lv1_1) and (or_ln757_fu_267_p2 = ap_const_lv1_1))) then
                icmp_ln824_reg_582 <= icmp_ln824_fu_297_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg) and (or_ln757_fu_267_p2 = ap_const_lv1_1))) then
                or_ln757_1_reg_578 <= or_ln757_1_fu_291_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((icmp_ln824_3_reg_618_pp0_iter10_reg = ap_const_lv1_0) and (icmp_ln824_2_reg_590_pp0_iter10_reg = ap_const_lv1_0) and (icmp_ln766_reg_594_pp0_iter10_reg = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln746_1_reg_622_pp0_iter10_reg) and (ap_const_lv1_0 = and_ln18_1_reg_602_pp0_iter10_reg) and (ap_const_lv1_0 = and_ln18_reg_598_pp0_iter10_reg) and (icmp_ln824_reg_582_pp0_iter10_reg = ap_const_lv1_0) and (or_ln757_1_reg_578_pp0_iter10_reg = ap_const_lv1_1) and (or_ln757_reg_574_pp0_iter10_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg)) or ((icmp_ln824_3_reg_618_pp0_iter10_reg = ap_const_lv1_0) and (icmp_ln824_2_reg_590_pp0_iter10_reg = ap_const_lv1_0) and (icmp_ln766_reg_594_pp0_iter10_reg = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln18_1_reg_602_pp0_iter10_reg) and (ap_const_lv1_0 = and_ln18_reg_598_pp0_iter10_reg) and (icmp_ln824_reg_582_pp0_iter10_reg = ap_const_lv1_0) and (or_ln757_1_reg_578_pp0_iter10_reg = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln746_1_reg_622_pp0_iter10_reg) and (or_ln757_reg_574_pp0_iter10_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg)))) then
                reg_191 <= grp_atan2_generic_float_s_fu_169_ap_return;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln766_reg_594_pp0_iter14_reg = ap_const_lv1_0) and (icmp_ln824_2_reg_590_pp0_iter14_reg = ap_const_lv1_0) and (ap_const_logic_1 = ap_ce_reg) and (icmp_ln824_reg_582_pp0_iter14_reg = ap_const_lv1_0) and (or_ln757_1_reg_578_pp0_iter14_reg = ap_const_lv1_1) and (or_ln757_reg_574_pp0_iter14_reg = ap_const_lv1_1))) then
                tmp_5_reg_631 <= tmp_5_fu_445_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                x_in_int_reg <= x_in;
                y_in_int_reg <= y_in;
            end if;
        end if;
    end process;
    a_reg_606(31) <= '0';
    b_reg_612(31) <= '0';
    a_fu_369_p1 <= zext_ln368_fu_365_p1;
    and_ln18_1_fu_355_p2 <= (icmp_ln828_fu_261_p2 and icmp_ln757_fu_249_p2);
    and_ln18_fu_349_p2 <= (icmp_ln828_1_fu_285_p2 and icmp_ln757_1_fu_273_p2);
    and_ln746_1_fu_439_p2 <= (tmp_10_fu_187_p2 and and_ln746_fu_433_p2);
    and_ln746_fu_433_p2 <= (or_ln746_fu_415_p2 and or_ln746_1_fu_427_p2);
    and_ln762_fu_303_p2 <= (p_Result_s_fu_201_p3 and icmp_ln828_fu_261_p2);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001_ignoreCallOp77 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state10_pp0_stage0_iter9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state10_pp0_stage0_iter9_ignore_call0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter10 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter10_ignore_call0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter11 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter11_ignore_call0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage0_iter12 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage0_iter12_ignore_call0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage0_iter13 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage0_iter13_ignore_call0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state15_pp0_stage0_iter14 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state15_pp0_stage0_iter14_ignore_call0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state16_pp0_stage0_iter15 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state16_pp0_stage0_iter15_ignore_call0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state17_pp0_stage0_iter16 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state17_pp0_stage0_iter16_ignore_call0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state18_pp0_stage0_iter17 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state18_pp0_stage0_iter17_ignore_call0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0_ignore_call0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3_ignore_call0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4_ignore_call0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5_ignore_call0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6_ignore_call0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7_ignore_call0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8_ignore_call0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_382_assign_proc : process(or_ln757_reg_574_pp0_iter13_reg, or_ln757_1_reg_578_pp0_iter13_reg, icmp_ln824_reg_582_pp0_iter13_reg, icmp_ln824_2_reg_590_pp0_iter13_reg, icmp_ln766_reg_594_pp0_iter13_reg, and_ln18_reg_598_pp0_iter13_reg, and_ln18_1_reg_602_pp0_iter13_reg, icmp_ln824_3_reg_618_pp0_iter13_reg, and_ln746_1_reg_622_pp0_iter13_reg)
    begin
                ap_condition_382 <= ((ap_const_lv1_0 = and_ln18_1_reg_602_pp0_iter13_reg) and (ap_const_lv1_0 = and_ln18_reg_598_pp0_iter13_reg) and (ap_const_lv1_1 = and_ln746_1_reg_622_pp0_iter13_reg) and (icmp_ln824_3_reg_618_pp0_iter13_reg = ap_const_lv1_0) and (icmp_ln766_reg_594_pp0_iter13_reg = ap_const_lv1_0) and (icmp_ln824_2_reg_590_pp0_iter13_reg = ap_const_lv1_0) and (icmp_ln824_reg_582_pp0_iter13_reg = ap_const_lv1_0) and (or_ln757_1_reg_578_pp0_iter13_reg = ap_const_lv1_1) and (or_ln757_reg_574_pp0_iter13_reg = ap_const_lv1_1));
    end process;


    ap_condition_415_assign_proc : process(or_ln757_reg_574_pp0_iter15_reg, or_ln757_1_reg_578_pp0_iter15_reg, icmp_ln824_reg_582_pp0_iter15_reg, icmp_ln824_2_reg_590_pp0_iter15_reg, icmp_ln766_reg_594_pp0_iter15_reg, and_ln18_reg_598_pp0_iter15_reg, and_ln18_1_reg_602_pp0_iter15_reg, tmp_5_reg_631)
    begin
                ap_condition_415 <= ((ap_const_lv1_0 = and_ln18_1_reg_602_pp0_iter15_reg) and (ap_const_lv1_0 = and_ln18_reg_598_pp0_iter15_reg) and (tmp_5_reg_631 = ap_const_lv2_1) and (icmp_ln766_reg_594_pp0_iter15_reg = ap_const_lv1_0) and (icmp_ln824_2_reg_590_pp0_iter15_reg = ap_const_lv1_0) and (icmp_ln824_reg_582_pp0_iter15_reg = ap_const_lv1_0) and (or_ln757_1_reg_578_pp0_iter15_reg = ap_const_lv1_1) and (or_ln757_reg_574_pp0_iter15_reg = ap_const_lv1_1));
    end process;


    ap_condition_420_assign_proc : process(or_ln757_reg_574_pp0_iter15_reg, or_ln757_1_reg_578_pp0_iter15_reg, icmp_ln824_reg_582_pp0_iter15_reg, icmp_ln824_2_reg_590_pp0_iter15_reg, icmp_ln766_reg_594_pp0_iter15_reg, and_ln18_reg_598_pp0_iter15_reg, and_ln18_1_reg_602_pp0_iter15_reg)
    begin
                ap_condition_420 <= ((ap_const_lv1_0 = and_ln18_reg_598_pp0_iter15_reg) and (ap_const_lv1_1 = and_ln18_1_reg_602_pp0_iter15_reg) and (icmp_ln766_reg_594_pp0_iter15_reg = ap_const_lv1_0) and (icmp_ln824_2_reg_590_pp0_iter15_reg = ap_const_lv1_0) and (icmp_ln824_reg_582_pp0_iter15_reg = ap_const_lv1_0) and (or_ln757_1_reg_578_pp0_iter15_reg = ap_const_lv1_1) and (or_ln757_reg_574_pp0_iter15_reg = ap_const_lv1_1));
    end process;


    ap_condition_425_assign_proc : process(or_ln757_reg_574_pp0_iter15_reg, or_ln757_1_reg_578_pp0_iter15_reg, icmp_ln824_reg_582_pp0_iter15_reg, icmp_ln824_2_reg_590_pp0_iter15_reg, icmp_ln766_reg_594_pp0_iter15_reg)
    begin
                ap_condition_425 <= ((icmp_ln766_reg_594_pp0_iter15_reg = ap_const_lv1_0) and (icmp_ln824_2_reg_590_pp0_iter15_reg = ap_const_lv1_1) and (icmp_ln824_reg_582_pp0_iter15_reg = ap_const_lv1_0) and (or_ln757_1_reg_578_pp0_iter15_reg = ap_const_lv1_1) and (or_ln757_reg_574_pp0_iter15_reg = ap_const_lv1_1));
    end process;


    ap_condition_437_assign_proc : process(p_Result_s_reg_553_pp0_iter15_reg, icmp_ln828_reg_570_pp0_iter15_reg, or_ln757_reg_574_pp0_iter15_reg, or_ln757_1_reg_578_pp0_iter15_reg, icmp_ln824_reg_582_pp0_iter15_reg, and_ln762_reg_586_pp0_iter15_reg, icmp_ln766_reg_594_pp0_iter15_reg)
    begin
                ap_condition_437 <= ((ap_const_lv1_0 = and_ln762_reg_586_pp0_iter15_reg) and (icmp_ln766_reg_594_pp0_iter15_reg = ap_const_lv1_0) and (icmp_ln824_reg_582_pp0_iter15_reg = ap_const_lv1_1) and (or_ln757_1_reg_578_pp0_iter15_reg = ap_const_lv1_1) and (or_ln757_reg_574_pp0_iter15_reg = ap_const_lv1_1) and (icmp_ln828_reg_570_pp0_iter15_reg = ap_const_lv1_0) and (p_Result_s_reg_553_pp0_iter15_reg = ap_const_lv1_0));
    end process;


    ap_condition_442_assign_proc : process(p_Result_s_reg_553_pp0_iter15_reg, icmp_ln828_reg_570_pp0_iter15_reg, or_ln757_reg_574_pp0_iter15_reg, or_ln757_1_reg_578_pp0_iter15_reg, icmp_ln824_reg_582_pp0_iter15_reg, and_ln762_reg_586_pp0_iter15_reg, icmp_ln766_reg_594_pp0_iter15_reg)
    begin
                ap_condition_442 <= ((ap_const_lv1_0 = and_ln762_reg_586_pp0_iter15_reg) and (icmp_ln766_reg_594_pp0_iter15_reg = ap_const_lv1_0) and (icmp_ln824_reg_582_pp0_iter15_reg = ap_const_lv1_1) and (or_ln757_1_reg_578_pp0_iter15_reg = ap_const_lv1_1) and (or_ln757_reg_574_pp0_iter15_reg = ap_const_lv1_1) and (icmp_ln828_reg_570_pp0_iter15_reg = ap_const_lv1_0) and (p_Result_s_reg_553_pp0_iter15_reg = ap_const_lv1_1));
    end process;


    ap_condition_451_assign_proc : process(icmp_ln828_reg_570_pp0_iter15_reg, or_ln757_reg_574_pp0_iter15_reg, or_ln757_1_reg_578_pp0_iter15_reg, icmp_ln824_reg_582_pp0_iter15_reg, and_ln762_reg_586_pp0_iter15_reg, icmp_ln766_reg_594_pp0_iter15_reg)
    begin
                ap_condition_451 <= (((icmp_ln766_reg_594_pp0_iter15_reg = ap_const_lv1_1) and (icmp_ln824_reg_582_pp0_iter15_reg = ap_const_lv1_0) and (or_ln757_1_reg_578_pp0_iter15_reg = ap_const_lv1_1) and (or_ln757_reg_574_pp0_iter15_reg = ap_const_lv1_1)) or ((ap_const_lv1_0 = and_ln762_reg_586_pp0_iter15_reg) and (icmp_ln766_reg_594_pp0_iter15_reg = ap_const_lv1_1) and (or_ln757_1_reg_578_pp0_iter15_reg = ap_const_lv1_1) and (or_ln757_reg_574_pp0_iter15_reg = ap_const_lv1_1) and (icmp_ln828_reg_570_pp0_iter15_reg = ap_const_lv1_0)));
    end process;


    ap_condition_456_assign_proc : process(icmp_ln828_reg_570_pp0_iter15_reg, or_ln757_reg_574_pp0_iter15_reg, or_ln757_1_reg_578_pp0_iter15_reg, icmp_ln824_reg_582_pp0_iter15_reg, and_ln762_reg_586_pp0_iter15_reg)
    begin
                ap_condition_456 <= ((ap_const_lv1_0 = and_ln762_reg_586_pp0_iter15_reg) and (icmp_ln824_reg_582_pp0_iter15_reg = ap_const_lv1_1) and (or_ln757_1_reg_578_pp0_iter15_reg = ap_const_lv1_1) and (or_ln757_reg_574_pp0_iter15_reg = ap_const_lv1_1) and (icmp_ln828_reg_570_pp0_iter15_reg = ap_const_lv1_1));
    end process;


    ap_condition_461_assign_proc : process(or_ln757_reg_574_pp0_iter15_reg, or_ln757_1_reg_578_pp0_iter15_reg, icmp_ln824_reg_582_pp0_iter15_reg, and_ln762_reg_586_pp0_iter15_reg)
    begin
                ap_condition_461 <= ((ap_const_lv1_1 = and_ln762_reg_586_pp0_iter15_reg) and (icmp_ln824_reg_582_pp0_iter15_reg = ap_const_lv1_1) and (or_ln757_1_reg_578_pp0_iter15_reg = ap_const_lv1_1) and (or_ln757_reg_574_pp0_iter15_reg = ap_const_lv1_1));
    end process;


    ap_condition_778_assign_proc : process(or_ln757_reg_574_pp0_iter11_reg, or_ln757_1_reg_578_pp0_iter11_reg, icmp_ln824_reg_582_pp0_iter11_reg, icmp_ln824_2_reg_590_pp0_iter11_reg, icmp_ln766_reg_594_pp0_iter11_reg, and_ln18_reg_598_pp0_iter11_reg, and_ln18_1_reg_602_pp0_iter11_reg, icmp_ln824_3_reg_618_pp0_iter11_reg, and_ln746_1_reg_622_pp0_iter11_reg)
    begin
                ap_condition_778 <= ((ap_const_lv1_0 = and_ln746_1_reg_622_pp0_iter11_reg) and (ap_const_lv1_0 = and_ln18_1_reg_602_pp0_iter11_reg) and (ap_const_lv1_0 = and_ln18_reg_598_pp0_iter11_reg) and (icmp_ln824_3_reg_618_pp0_iter11_reg = ap_const_lv1_0) and (icmp_ln766_reg_594_pp0_iter11_reg = ap_const_lv1_0) and (icmp_ln824_2_reg_590_pp0_iter11_reg = ap_const_lv1_0) and (icmp_ln824_reg_582_pp0_iter11_reg = ap_const_lv1_0) and (or_ln757_1_reg_578_pp0_iter11_reg = ap_const_lv1_1) and (or_ln757_reg_574_pp0_iter11_reg = ap_const_lv1_1));
    end process;


    ap_condition_782_assign_proc : process(or_ln757_fu_267_p2, or_ln757_1_fu_291_p2, icmp_ln824_fu_297_p2, icmp_ln824_2_fu_309_p2, icmp_ln766_fu_343_p2, and_ln18_fu_349_p2, and_ln18_1_fu_355_p2, icmp_ln824_3_fu_403_p2)
    begin
                ap_condition_782 <= ((ap_const_lv1_0 = and_ln18_1_fu_355_p2) and (ap_const_lv1_0 = and_ln18_fu_349_p2) and (icmp_ln824_3_fu_403_p2 = ap_const_lv1_1) and (icmp_ln766_fu_343_p2 = ap_const_lv1_0) and (icmp_ln824_2_fu_309_p2 = ap_const_lv1_0) and (icmp_ln824_fu_297_p2 = ap_const_lv1_0) and (or_ln757_1_fu_291_p2 = ap_const_lv1_1) and (or_ln757_fu_267_p2 = ap_const_lv1_1));
    end process;


    ap_condition_810_assign_proc : process(or_ln757_reg_574_pp0_iter14_reg, or_ln757_1_reg_578_pp0_iter14_reg, icmp_ln824_reg_582_pp0_iter14_reg, icmp_ln824_2_reg_590_pp0_iter14_reg, icmp_ln766_reg_594_pp0_iter14_reg, and_ln18_reg_598_pp0_iter14_reg, and_ln18_1_reg_602_pp0_iter14_reg, tmp_5_fu_445_p3)
    begin
                ap_condition_810 <= ((ap_const_lv1_1 = and_ln18_1_reg_602_pp0_iter14_reg) and (ap_const_lv1_1 = and_ln18_reg_598_pp0_iter14_reg) and (tmp_5_fu_445_p3 = ap_const_lv2_3) and (icmp_ln766_reg_594_pp0_iter14_reg = ap_const_lv1_0) and (icmp_ln824_2_reg_590_pp0_iter14_reg = ap_const_lv1_0) and (icmp_ln824_reg_582_pp0_iter14_reg = ap_const_lv1_0) and (or_ln757_1_reg_578_pp0_iter14_reg = ap_const_lv1_1) and (or_ln757_reg_574_pp0_iter14_reg = ap_const_lv1_1));
    end process;


    ap_condition_815_assign_proc : process(or_ln757_reg_574_pp0_iter14_reg, or_ln757_1_reg_578_pp0_iter14_reg, icmp_ln824_reg_582_pp0_iter14_reg, icmp_ln824_2_reg_590_pp0_iter14_reg, icmp_ln766_reg_594_pp0_iter14_reg, and_ln18_reg_598_pp0_iter14_reg, and_ln18_1_reg_602_pp0_iter14_reg, tmp_5_fu_445_p3)
    begin
                ap_condition_815 <= ((ap_const_lv1_1 = and_ln18_1_reg_602_pp0_iter14_reg) and (ap_const_lv1_1 = and_ln18_reg_598_pp0_iter14_reg) and (tmp_5_fu_445_p3 = ap_const_lv2_2) and (icmp_ln766_reg_594_pp0_iter14_reg = ap_const_lv1_0) and (icmp_ln824_2_reg_590_pp0_iter14_reg = ap_const_lv1_0) and (icmp_ln824_reg_582_pp0_iter14_reg = ap_const_lv1_0) and (or_ln757_1_reg_578_pp0_iter14_reg = ap_const_lv1_1) and (or_ln757_reg_574_pp0_iter14_reg = ap_const_lv1_1));
    end process;


    ap_condition_819_assign_proc : process(or_ln757_reg_574_pp0_iter14_reg, or_ln757_1_reg_578_pp0_iter14_reg, icmp_ln824_reg_582_pp0_iter14_reg, icmp_ln824_2_reg_590_pp0_iter14_reg, icmp_ln766_reg_594_pp0_iter14_reg, and_ln18_reg_598_pp0_iter14_reg, and_ln18_1_reg_602_pp0_iter14_reg, tmp_5_fu_445_p3)
    begin
                ap_condition_819 <= ((ap_const_lv1_1 = and_ln18_1_reg_602_pp0_iter14_reg) and (ap_const_lv1_1 = and_ln18_reg_598_pp0_iter14_reg) and (tmp_5_fu_445_p3 = ap_const_lv2_1) and (icmp_ln766_reg_594_pp0_iter14_reg = ap_const_lv1_0) and (icmp_ln824_2_reg_590_pp0_iter14_reg = ap_const_lv1_0) and (icmp_ln824_reg_582_pp0_iter14_reg = ap_const_lv1_0) and (or_ln757_1_reg_578_pp0_iter14_reg = ap_const_lv1_1) and (or_ln757_reg_574_pp0_iter14_reg = ap_const_lv1_1));
    end process;


    ap_condition_824_assign_proc : process(or_ln757_reg_574_pp0_iter14_reg, or_ln757_1_reg_578_pp0_iter14_reg, icmp_ln824_reg_582_pp0_iter14_reg, icmp_ln824_2_reg_590_pp0_iter14_reg, icmp_ln766_reg_594_pp0_iter14_reg, and_ln18_reg_598_pp0_iter14_reg, and_ln18_1_reg_602_pp0_iter14_reg, tmp_5_fu_445_p3)
    begin
                ap_condition_824 <= ((ap_const_lv1_0 = and_ln18_1_reg_602_pp0_iter14_reg) and (ap_const_lv1_1 = and_ln18_reg_598_pp0_iter14_reg) and (tmp_5_fu_445_p3 = ap_const_lv2_3) and (icmp_ln766_reg_594_pp0_iter14_reg = ap_const_lv1_0) and (icmp_ln824_2_reg_590_pp0_iter14_reg = ap_const_lv1_0) and (icmp_ln824_reg_582_pp0_iter14_reg = ap_const_lv1_0) and (or_ln757_1_reg_578_pp0_iter14_reg = ap_const_lv1_1) and (or_ln757_reg_574_pp0_iter14_reg = ap_const_lv1_1));
    end process;


    ap_condition_827_assign_proc : process(or_ln757_reg_574_pp0_iter14_reg, or_ln757_1_reg_578_pp0_iter14_reg, icmp_ln824_reg_582_pp0_iter14_reg, icmp_ln824_2_reg_590_pp0_iter14_reg, icmp_ln766_reg_594_pp0_iter14_reg, and_ln18_reg_598_pp0_iter14_reg, and_ln18_1_reg_602_pp0_iter14_reg, tmp_5_fu_445_p3)
    begin
                ap_condition_827 <= ((ap_const_lv1_0 = and_ln18_1_reg_602_pp0_iter14_reg) and (ap_const_lv1_1 = and_ln18_reg_598_pp0_iter14_reg) and (tmp_5_fu_445_p3 = ap_const_lv2_2) and (icmp_ln766_reg_594_pp0_iter14_reg = ap_const_lv1_0) and (icmp_ln824_2_reg_590_pp0_iter14_reg = ap_const_lv1_0) and (icmp_ln824_reg_582_pp0_iter14_reg = ap_const_lv1_0) and (or_ln757_1_reg_578_pp0_iter14_reg = ap_const_lv1_1) and (or_ln757_reg_574_pp0_iter14_reg = ap_const_lv1_1));
    end process;


    ap_condition_830_assign_proc : process(or_ln757_reg_574_pp0_iter14_reg, or_ln757_1_reg_578_pp0_iter14_reg, icmp_ln824_reg_582_pp0_iter14_reg, icmp_ln824_2_reg_590_pp0_iter14_reg, icmp_ln766_reg_594_pp0_iter14_reg, and_ln18_reg_598_pp0_iter14_reg, and_ln18_1_reg_602_pp0_iter14_reg, tmp_5_fu_445_p3)
    begin
                ap_condition_830 <= ((ap_const_lv1_0 = and_ln18_1_reg_602_pp0_iter14_reg) and (ap_const_lv1_1 = and_ln18_reg_598_pp0_iter14_reg) and (tmp_5_fu_445_p3 = ap_const_lv2_1) and (icmp_ln766_reg_594_pp0_iter14_reg = ap_const_lv1_0) and (icmp_ln824_2_reg_590_pp0_iter14_reg = ap_const_lv1_0) and (icmp_ln824_reg_582_pp0_iter14_reg = ap_const_lv1_0) and (or_ln757_1_reg_578_pp0_iter14_reg = ap_const_lv1_1) and (or_ln757_reg_574_pp0_iter14_reg = ap_const_lv1_1));
    end process;


    ap_condition_845_assign_proc : process(or_ln757_reg_574_pp0_iter16_reg, or_ln757_1_reg_578_pp0_iter16_reg, icmp_ln824_reg_582_pp0_iter16_reg, icmp_ln824_2_reg_590_pp0_iter16_reg, icmp_ln766_reg_594_pp0_iter16_reg, and_ln18_reg_598_pp0_iter16_reg, and_ln18_1_reg_602_pp0_iter16_reg)
    begin
                ap_condition_845 <= ((ap_const_lv1_0 = and_ln18_1_reg_602_pp0_iter16_reg) and (ap_const_lv1_0 = and_ln18_reg_598_pp0_iter16_reg) and (icmp_ln766_reg_594_pp0_iter16_reg = ap_const_lv1_0) and (icmp_ln824_2_reg_590_pp0_iter16_reg = ap_const_lv1_0) and (icmp_ln824_reg_582_pp0_iter16_reg = ap_const_lv1_0) and (or_ln757_1_reg_578_pp0_iter16_reg = ap_const_lv1_1) and (or_ln757_reg_574_pp0_iter16_reg = ap_const_lv1_1));
    end process;


    ap_condition_858_assign_proc : process(or_ln757_reg_574_pp0_iter14_reg, or_ln757_1_reg_578_pp0_iter14_reg, icmp_ln824_reg_582_pp0_iter14_reg, icmp_ln824_2_reg_590_pp0_iter14_reg, icmp_ln766_reg_594_pp0_iter14_reg, and_ln18_reg_598_pp0_iter14_reg, and_ln18_1_reg_602_pp0_iter14_reg, tmp_5_fu_445_p3)
    begin
                ap_condition_858 <= ((ap_const_lv1_0 = and_ln18_1_reg_602_pp0_iter14_reg) and (ap_const_lv1_0 = and_ln18_reg_598_pp0_iter14_reg) and (tmp_5_fu_445_p3 = ap_const_lv2_0) and (icmp_ln766_reg_594_pp0_iter14_reg = ap_const_lv1_0) and (icmp_ln824_2_reg_590_pp0_iter14_reg = ap_const_lv1_0) and (icmp_ln824_reg_582_pp0_iter14_reg = ap_const_lv1_0) and (or_ln757_1_reg_578_pp0_iter14_reg = ap_const_lv1_1) and (or_ln757_reg_574_pp0_iter14_reg = ap_const_lv1_1));
    end process;


    ap_condition_860_assign_proc : process(or_ln757_reg_574_pp0_iter14_reg, or_ln757_1_reg_578_pp0_iter14_reg, icmp_ln824_reg_582_pp0_iter14_reg, icmp_ln824_2_reg_590_pp0_iter14_reg, icmp_ln766_reg_594_pp0_iter14_reg, and_ln18_reg_598_pp0_iter14_reg, and_ln18_1_reg_602_pp0_iter14_reg, tmp_5_fu_445_p3)
    begin
                ap_condition_860 <= ((ap_const_lv1_1 = and_ln18_1_reg_602_pp0_iter14_reg) and (ap_const_lv1_1 = and_ln18_reg_598_pp0_iter14_reg) and (tmp_5_fu_445_p3 = ap_const_lv2_0) and (icmp_ln766_reg_594_pp0_iter14_reg = ap_const_lv1_0) and (icmp_ln824_2_reg_590_pp0_iter14_reg = ap_const_lv1_0) and (icmp_ln824_reg_582_pp0_iter14_reg = ap_const_lv1_0) and (or_ln757_1_reg_578_pp0_iter14_reg = ap_const_lv1_1) and (or_ln757_reg_574_pp0_iter14_reg = ap_const_lv1_1));
    end process;


    ap_condition_863_assign_proc : process(or_ln757_reg_574_pp0_iter14_reg, or_ln757_1_reg_578_pp0_iter14_reg, icmp_ln824_reg_582_pp0_iter14_reg, icmp_ln824_2_reg_590_pp0_iter14_reg, icmp_ln766_reg_594_pp0_iter14_reg, and_ln18_reg_598_pp0_iter14_reg, and_ln18_1_reg_602_pp0_iter14_reg, tmp_5_fu_445_p3)
    begin
                ap_condition_863 <= ((ap_const_lv1_0 = and_ln18_1_reg_602_pp0_iter14_reg) and (ap_const_lv1_1 = and_ln18_reg_598_pp0_iter14_reg) and (tmp_5_fu_445_p3 = ap_const_lv2_0) and (icmp_ln766_reg_594_pp0_iter14_reg = ap_const_lv1_0) and (icmp_ln824_2_reg_590_pp0_iter14_reg = ap_const_lv1_0) and (icmp_ln824_reg_582_pp0_iter14_reg = ap_const_lv1_0) and (or_ln757_1_reg_578_pp0_iter14_reg = ap_const_lv1_1) and (or_ln757_reg_574_pp0_iter14_reg = ap_const_lv1_1));
    end process;


    ap_phi_mux_UnifiedRetVal_phi_fu_114_p42_assign_proc : process(tmp_5_reg_631_pp0_iter16_reg, ap_phi_reg_pp0_iter17_UnifiedRetVal_reg_102, bitcast_ln826_1_fu_548_p1, grp_fu_180_p2, ap_condition_845)
    begin
        if ((ap_const_boolean_1 = ap_condition_845)) then
            if ((tmp_5_reg_631_pp0_iter16_reg = ap_const_lv2_2)) then 
                ap_phi_mux_UnifiedRetVal_phi_fu_114_p42 <= grp_fu_180_p2;
            elsif ((tmp_5_reg_631_pp0_iter16_reg = ap_const_lv2_3)) then 
                ap_phi_mux_UnifiedRetVal_phi_fu_114_p42 <= bitcast_ln826_1_fu_548_p1;
            else 
                ap_phi_mux_UnifiedRetVal_phi_fu_114_p42 <= ap_phi_reg_pp0_iter17_UnifiedRetVal_reg_102;
            end if;
        else 
            ap_phi_mux_UnifiedRetVal_phi_fu_114_p42 <= ap_phi_reg_pp0_iter17_UnifiedRetVal_reg_102;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_UnifiedRetVal_reg_102 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_c_reg_88 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

    ap_predicate_op77_call_state2_assign_proc : process(or_ln757_reg_574, or_ln757_1_reg_578, icmp_ln824_reg_582, icmp_ln766_reg_594, icmp_ln824_2_reg_590, and_ln18_reg_598, and_ln18_1_reg_602, icmp_ln824_3_reg_618, and_ln746_1_reg_622)
    begin
                ap_predicate_op77_call_state2 <= ((icmp_ln824_3_reg_618 = ap_const_lv1_0) and (icmp_ln824_2_reg_590 = ap_const_lv1_0) and (icmp_ln766_reg_594 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln746_1_reg_622) and (ap_const_lv1_0 = and_ln18_1_reg_602) and (ap_const_lv1_0 = and_ln18_reg_598) and (icmp_ln824_reg_582 = ap_const_lv1_0) and (or_ln757_1_reg_578 = ap_const_lv1_1) and (or_ln757_reg_574 = ap_const_lv1_1));
    end process;


    ap_predicate_op78_call_state2_assign_proc : process(or_ln757_reg_574, or_ln757_1_reg_578, icmp_ln824_reg_582, icmp_ln766_reg_594, icmp_ln824_2_reg_590, and_ln18_reg_598, and_ln18_1_reg_602, icmp_ln824_3_reg_618, and_ln746_1_reg_622)
    begin
                ap_predicate_op78_call_state2 <= ((icmp_ln824_3_reg_618 = ap_const_lv1_0) and (icmp_ln824_2_reg_590 = ap_const_lv1_0) and (icmp_ln766_reg_594 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln18_1_reg_602) and (ap_const_lv1_0 = and_ln18_reg_598) and (icmp_ln824_reg_582 = ap_const_lv1_0) and (or_ln757_1_reg_578 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln746_1_reg_622) and (or_ln757_reg_574 = ap_const_lv1_1));
    end process;


    ap_return_assign_proc : process(ap_phi_mux_UnifiedRetVal_phi_fu_114_p42, ap_ce_reg, ap_return_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return <= ap_return_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return <= ap_phi_mux_UnifiedRetVal_phi_fu_114_p42;
        end if; 
    end process;

    b_fu_382_p1 <= zext_ln368_1_fu_378_p1;
    bitcast_ln351_1_fu_523_p1 <= p_Result_33_fu_516_p3;
    bitcast_ln351_2_fu_512_p1 <= p_Result_34_fu_505_p3;
    bitcast_ln351_3_fu_501_p1 <= p_Result_35_fu_494_p3;
    bitcast_ln351_4_fu_490_p1 <= p_Result_36_fu_483_p3;
    bitcast_ln351_5_fu_479_p1 <= p_Result_37_fu_472_p3;
    bitcast_ln351_fu_534_p1 <= p_Result_32_fu_527_p3;
    bitcast_ln822_1_fu_461_p1 <= xor_ln822_fu_455_p2;
    bitcast_ln822_fu_451_p1 <= c_reg_88;
    bitcast_ln826_1_fu_548_p1 <= xor_ln826_fu_542_p2;
    bitcast_ln826_fu_538_p1 <= grp_fu_180_p2;
    data_V_2_fu_223_p1 <= y_in_int_reg;
    data_V_fu_197_p1 <= x_in_int_reg;

    grp_atan2_generic_float_s_fu_169_ap_ce_assign_proc : process(ap_block_pp0_stage0_11001_ignoreCallOp77, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp77) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_atan2_generic_float_s_fu_169_ap_ce <= ap_const_logic_1;
        else 
            grp_atan2_generic_float_s_fu_169_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_atan2_generic_float_s_fu_169_x_in_assign_proc : process(a_reg_606, b_reg_612, ap_predicate_op77_call_state2, ap_predicate_op78_call_state2, ap_block_pp0_stage0)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0)) then
            if ((ap_predicate_op78_call_state2 = ap_const_boolean_1)) then 
                grp_atan2_generic_float_s_fu_169_x_in <= a_reg_606;
            elsif ((ap_predicate_op77_call_state2 = ap_const_boolean_1)) then 
                grp_atan2_generic_float_s_fu_169_x_in <= b_reg_612;
            else 
                grp_atan2_generic_float_s_fu_169_x_in <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            grp_atan2_generic_float_s_fu_169_x_in <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_atan2_generic_float_s_fu_169_y_in_assign_proc : process(a_reg_606, b_reg_612, ap_predicate_op77_call_state2, ap_predicate_op78_call_state2, ap_block_pp0_stage0)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0)) then
            if ((ap_predicate_op78_call_state2 = ap_const_boolean_1)) then 
                grp_atan2_generic_float_s_fu_169_y_in <= b_reg_612;
            elsif ((ap_predicate_op77_call_state2 = ap_const_boolean_1)) then 
                grp_atan2_generic_float_s_fu_169_y_in <= a_reg_606;
            else 
                grp_atan2_generic_float_s_fu_169_y_in <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            grp_atan2_generic_float_s_fu_169_y_in <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_175_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_175_ce <= ap_const_logic_1;
        else 
            grp_fu_175_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_180_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_180_ce <= ap_const_logic_1;
        else 
            grp_fu_180_ce <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln746_1_fu_421_p2 <= "0" when (tmp_fu_209_p4 = ap_const_lv8_FF) else "1";
    icmp_ln746_fu_409_p2 <= "0" when (tmp_79_fu_235_p4 = ap_const_lv8_FF) else "1";
    icmp_ln757_1_fu_273_p2 <= "1" when (tmp_fu_209_p4 = ap_const_lv8_FF) else "0";
    icmp_ln757_fu_249_p2 <= "1" when (tmp_79_fu_235_p4 = ap_const_lv8_FF) else "0";
    icmp_ln766_fu_343_p2 <= "1" when (tmp_4_fu_335_p3 = ap_const_lv23_0) else "0";
    icmp_ln824_2_fu_309_p2 <= "1" when (tmp_fu_209_p4 = ap_const_lv8_0) else "0";
    icmp_ln824_3_fu_403_p2 <= "1" when (p_Result_40_fu_387_p3 = p_Result_41_fu_395_p3) else "0";
    icmp_ln824_fu_297_p2 <= "1" when (tmp_79_fu_235_p4 = ap_const_lv8_0) else "0";
    icmp_ln828_1_fu_285_p2 <= "1" when (tmp_78_fu_219_p1 = ap_const_lv23_0) else "0";
    icmp_ln828_fu_261_p2 <= "1" when (tmp_80_fu_245_p1 = ap_const_lv23_0) else "0";
    or_ln746_1_fu_427_p2 <= (icmp_ln828_1_fu_285_p2 or icmp_ln746_1_fu_421_p2);
    or_ln746_fu_415_p2 <= (icmp_ln828_fu_261_p2 or icmp_ln746_fu_409_p2);
    or_ln757_1_fu_291_p2 <= (xor_ln18_1_fu_279_p2 or icmp_ln828_1_fu_285_p2);
    or_ln757_fu_267_p2 <= (xor_ln18_fu_255_p2 or icmp_ln828_fu_261_p2);
    or_ln766_fu_319_p2 <= (trunc_ln766_fu_315_p1 or tmp_fu_209_p4);
    p_Result_32_fu_527_p3 <= (p_Result_31_reg_558_pp0_iter15_reg & ap_const_lv31_40490FDB);
    p_Result_33_fu_516_p3 <= (p_Result_31_reg_558_pp0_iter15_reg & ap_const_lv31_0);
    p_Result_34_fu_505_p3 <= (p_Result_31_reg_558_pp0_iter15_reg & ap_const_lv31_3FC90FDB);
    p_Result_35_fu_494_p3 <= (p_Result_31_reg_558_pp0_iter15_reg & ap_const_lv31_40490FDB);
    p_Result_36_fu_483_p3 <= (p_Result_31_reg_558_pp0_iter15_reg & ap_const_lv31_0);
    p_Result_37_fu_472_p3 <= (p_Result_31_reg_558_pp0_iter15_reg & ap_const_lv31_3FC90FDB);
    p_Result_38_fu_361_p1 <= data_V_2_fu_223_p1(31 - 1 downto 0);
    p_Result_39_fu_374_p1 <= data_V_fu_197_p1(31 - 1 downto 0);
    p_Result_40_fu_387_p3 <= (ap_const_lv1_0 & p_Result_39_fu_374_p1);
    p_Result_41_fu_395_p3 <= (ap_const_lv1_0 & p_Result_38_fu_361_p1);
    p_Result_s_fu_201_p3 <= data_V_fu_197_p1(31 downto 31);
    select_ln809_fu_465_p3 <= 
        ap_const_lv32_BFC90FDB when (p_Result_31_reg_558_pp0_iter15_reg(0) = '1') else 
        ap_const_lv32_3FC90FDB;
    tmp_10_fu_187_p0 <= zext_ln368_fu_365_p1;
    tmp_10_fu_187_p1 <= zext_ln368_1_fu_378_p1;
    tmp_3_fu_325_p4 <= data_V_fu_197_p1(22 downto 8);
    tmp_4_fu_335_p3 <= (tmp_3_fu_325_p4 & or_ln766_fu_319_p2);
    tmp_5_fu_445_p3 <= (p_Result_s_reg_553_pp0_iter14_reg & p_Result_31_reg_558_pp0_iter14_reg);
    tmp_78_fu_219_p1 <= data_V_fu_197_p1(23 - 1 downto 0);
    tmp_79_fu_235_p4 <= data_V_2_fu_223_p1(30 downto 23);
    tmp_80_fu_245_p1 <= data_V_2_fu_223_p1(23 - 1 downto 0);
    tmp_fu_209_p4 <= data_V_fu_197_p1(30 downto 23);
    trunc_ln766_fu_315_p1 <= data_V_fu_197_p1(8 - 1 downto 0);
    xor_ln18_1_fu_279_p2 <= (icmp_ln757_1_fu_273_p2 xor ap_const_lv1_1);
    xor_ln18_fu_255_p2 <= (icmp_ln757_fu_249_p2 xor ap_const_lv1_1);
    xor_ln822_fu_455_p2 <= (bitcast_ln822_fu_451_p1 xor ap_const_lv32_80000000);
    xor_ln826_fu_542_p2 <= (bitcast_ln826_fu_538_p1 xor ap_const_lv32_80000000);
    zext_ln368_1_fu_378_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_39_fu_374_p1),32));
    zext_ln368_fu_365_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_38_fu_361_p1),32));
end behav;
