# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-3848-ubuntu/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xcvu37p-fsvh2892-2L-e
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/xdma_bpu_ex.gen/sources_1/ip/ddc_out_fifo/hdl
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/xdma_bpu_ex.gen/sources_1/ip/axis_fifo_t/hdl
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/parameters
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/rs_encoder
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/add_duc
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/dds_125m_i
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/dds_125m_q
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/duc_out_fifo
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/mult_duc
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/sub_duc
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/axis_fifo_t8
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/receive/rs_decoder
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/receive/add_ddc
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/receive/dds_ri
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/receive/dds_rq
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/receive/mult_ddc
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/receive/sub_ddc
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/xdma_bpu_ex.srcs/sources_1/ip/apskdemod64
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/xdma_bpu_ex.srcs/sources_1/ip/bbp_mmc
  } {
      /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/xdma_bpu_ex.srcs/sources_1/new/apskdemod_call.sv
      /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/receive/bbp_receive.sv
      /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/bbp_transmit.sv
      /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/receive/crc_detector.sv
      /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/crc_generator.sv
      /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/receive/data_transfer.sv
      /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/datastream_transfer.sv
      /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/receive/ddc.sv
      /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/receive/deintrlv.sv
      /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/receive/descrambler.sv
      /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/duc.sv
      /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/receive/eqam.sv
      /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/interleaver.sv
      /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/receive/layer1_pull.sv
      /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/layer1_push.sv
      /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/receive/layer1_receive.sv
      /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/layer1_transmit.sv
      /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/mac_block.sv
      /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/receive/mac_deblock.sv
      /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/qam.sv
      /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/receive/radio_pull.sv
      /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/radio_push.sv
      /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/receive/radio_receive.sv
      /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/radio_transmit.sv
      /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/scrambler.sv
      /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/receive/tpu_pullstream.sv
      /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/tpu_pushstream.sv
      /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/xdma_bpu_ex.srcs/sources_1/new/baseband_processor.sv
    }
      rt::read_verilog -sv -include {
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/xdma_bpu_ex.gen/sources_1/ip/ddc_out_fifo/hdl
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/xdma_bpu_ex.gen/sources_1/ip/axis_fifo_t/hdl
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/parameters
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/rs_encoder
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/add_duc
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/dds_125m_i
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/dds_125m_q
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/duc_out_fifo
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/mult_duc
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/sub_duc
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/axis_fifo_t8
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/receive/rs_decoder
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/receive/add_ddc
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/receive/dds_ri
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/receive/dds_rq
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/receive/mult_ddc
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/receive/sub_ddc
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/xdma_bpu_ex.srcs/sources_1/ip/apskdemod64
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/xdma_bpu_ex.srcs/sources_1/ip/bbp_mmc
  } {
      /tools/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /tools/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      /tools/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/xdma_bpu_ex.gen/sources_1/ip/ddc_out_fifo/hdl
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/xdma_bpu_ex.gen/sources_1/ip/axis_fifo_t/hdl
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/parameters
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/rs_encoder
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/add_duc
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/dds_125m_i
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/dds_125m_q
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/duc_out_fifo
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/mult_duc
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/sub_duc
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/axis_fifo_t8
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/receive/rs_decoder
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/receive/add_ddc
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/receive/dds_ri
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/receive/dds_rq
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/receive/mult_ddc
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/receive/sub_ddc
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/xdma_bpu_ex.srcs/sources_1/ip/apskdemod64
    /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/xdma_bpu_ex.srcs/sources_1/ip/bbp_mmc
  } {
      ./.Xil/Vivado-3848-ubuntu/realtime/ddc_out_fifo_stub.v
      ./.Xil/Vivado-3848-ubuntu/realtime/axis_fifo_t_stub.v
      ./.Xil/Vivado-3848-ubuntu/realtime/rs_encoder_stub.v
      ./.Xil/Vivado-3848-ubuntu/realtime/add_duc_stub.v
      ./.Xil/Vivado-3848-ubuntu/realtime/dds_125m_i_stub.v
      ./.Xil/Vivado-3848-ubuntu/realtime/dds_125m_q_stub.v
      ./.Xil/Vivado-3848-ubuntu/realtime/duc_out_fifo_stub.v
      ./.Xil/Vivado-3848-ubuntu/realtime/mult_duc_stub.v
      ./.Xil/Vivado-3848-ubuntu/realtime/sub_duc_stub.v
      ./.Xil/Vivado-3848-ubuntu/realtime/axis_fifo_t8_stub.v
      ./.Xil/Vivado-3848-ubuntu/realtime/rs_decoder_stub.v
      ./.Xil/Vivado-3848-ubuntu/realtime/add_ddc_stub.v
      ./.Xil/Vivado-3848-ubuntu/realtime/dds_ri_stub.v
      ./.Xil/Vivado-3848-ubuntu/realtime/dds_rq_stub.v
      ./.Xil/Vivado-3848-ubuntu/realtime/mult_ddc_stub.v
      ./.Xil/Vivado-3848-ubuntu/realtime/sub_ddc_stub.v
      ./.Xil/Vivado-3848-ubuntu/realtime/apskdemod64_stub.v
      ./.Xil/Vivado-3848-ubuntu/realtime/bbp_mmc_stub.v
      /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/crc24_calc_1bit.v
      /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/crc24_insert_1bit.v
    }
      rt::read_vhdl -lib xpm /tools/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top baseband_processor
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-3848-ubuntu/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
