# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/xdma_bpu_ex.srcs/sources_1/ip/encoders/encoders.xci
# IP: The module: 'encoders' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/xdma_bpu_ex.gen/sources_1/ip/encoders/constraints/encode_rs_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'encoders'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/xdma_bpu_ex.srcs/sources_1/ip/encoders/encoders.xci
# IP: The module: 'encoders' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/xdma_bpu_ex.gen/sources_1/ip/encoders/constraints/encode_rs_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'encoders'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
