# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/axis_fifo_t8/axis_fifo_t8.xci
# IP: The module: 'axis_fifo_t8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/axis_fifo_t8/axis_fifo_t8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_fifo_t8'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/axis_fifo_t8/axis_fifo_t8.xci
# IP: The module: 'axis_fifo_t8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/axis_fifo_t8/axis_fifo_t8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_fifo_t8'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
