# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/duc_out_fifo/duc_out_fifo.xci
# IP: The module: 'duc_out_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/duc_out_fifo/duc_out_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'duc_out_fifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/duc_out_fifo/duc_out_fifo.xci
# IP: The module: 'duc_out_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/caohy168/Work/bbp_vcu128/xdma_bpu_ex/imports/bbp/transmit/duc_out_fifo/duc_out_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'duc_out_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
